In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [3]:
a.dtype

dtype('int64')

In [4]:
r=np.random.rand(3,3)
r

array([[0.48675512, 0.78083548, 0.7004911 ],
       [0.33151595, 0.73153701, 0.2853902 ],
       [0.69288255, 0.29883143, 0.50110731]])

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr.ndim

1

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.shape
arr.size

10

In [9]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(3, 3)

In [14]:
import numpy as np
arr3=np.array([[[1,2,3,0],[4,5,6,4],[7,8,9,10]],
        [[7,4,1,5],[8,5,2,1],[9,6,3,5]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
arr3[0][1]

[[[ 1  2  3  0]
  [ 4  5  6  4]
  [ 7  8  9 10]]

 [[ 7  4  1  5]
  [ 8  5  2  1]
  [ 9  6  3  5]]]
3
(2, 3, 4)


array([4, 5, 6, 4])

In [4]:
c=np.array(1)
np.ndim(c)

0

In [5]:
b=np.array([[1,2,3,4],[3,5,6,7]])
b
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [3, 5],
       [6, 7]])

In [9]:
b[0][3]


np.int64(7)

In [10]:
b[1][3]

np.int64(7)

In [13]:
b[0][2]

np.int64(3)

In [16]:
v=np.arange(1,100)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
v=np.arange(0,100,2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
v=np.arange(1,100,2)
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
#create evenly spaced value:
import numpy as np
c=np.linspace(1,5,4)
c

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [6]:
arr3=np.array([[[1,2,3,0],[4,5,6,4],[7,8,9,10]],
        [[7,4,1,5],[8,5,2,1],[9,6,3,5]]])
arr3[0][2][3]


np.int64(10)

In [8]:
#mathimatical funtions to access array
v=np.arange(1,100)
np.sum(v)

np.int64(4950)

In [13]:
print(np.mean(v))
print(np.median(v))
print(np.std(v))
print(np.min(v))
print(np.max(v))
print((np.var(v)))

50.0
50.0
28.577380332470412
1
99
816.6666666666666


In [17]:
#random num generate:
np.random.seed(1)  #seed used to generte same random num
np.random.rand(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [15]:
np.random.randint(1,100,5)

array([ 6, 13, 44, 13, 37], dtype=int32)

In [18]:
np.random.seed(1)

In [20]:
#forword slicing:
a=np.array([10,20,30,40,50])
a[2] #indexing
a[0:3]

array([10, 20, 30])

In [22]:
b=np.arange(1,50)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
b[18:22]

array([19, 20, 21, 22])

In [26]:
#negative slicing
c=np.array([1,2,3,4,5])
c[:-1]


array([1, 2, 3, 4])

In [28]:
e=np.array([6,3,9,1,2])
print(e[:-3]) #3 indes cut from backward
print(e[-3]) #give index value 

[6 3]
9


In [29]:
#filtering
e[e>2]

array([6, 3, 9])

In [33]:
import numpy as np
a1=np.arange(1,11)
a2=np.arange(15,25)
print(a1)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[15 16 17 18 19 20 21 22 23 24]


In [36]:
import numpy as np
np.concatenate((a1,a2))  #join

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [37]:
np.split(a1,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [38]:
np.sort(a2)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
print(a1+a2) #add upper value and lower
print(a1*a2) #mul up down
print(np.dot(a1,a2)) #mul all
print(a1/a2)

[16 18 20 22 24 26 28 30 32 34]
[ 15  32  51  72  95 120 147 176 207 240]
1155
[0.06666667 0.125      0.17647059 0.22222222 0.26315789 0.3
 0.33333333 0.36363636 0.39130435 0.41666667]


In [51]:
y=np.array([[1,2],[3,4]])
print(y.reshape(-1,1))
print(y.reshape(1,-1))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [48]:
np.ravel(y)

array([1, 2, 3, 4])

In [50]:
y.flatten()

array([1, 2, 3, 4])