In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
arr2=np.zeros((5,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
arr3=np.identity(4)
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr4=np.random.randint(10,101,15)
(arr4)

array([11, 31, 59, 66, 69, 11, 62, 11, 45, 50, 53, 76, 72, 63, 99],
      dtype=int32)

In [12]:
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)

(15,)
15
int32


In [14]:
arr5=np.arange(1,25)
reshape=arr5.reshape(4,6)
print(arr5)
print(reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
arr6=np.array([[1,2,3],[4,5,6]])
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
oneD=arr6.flatten()
oneD

array([1, 2, 3, 4, 5, 6])

In [22]:
even=np.arange(2,51,2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [23]:
mul=np.arange(0,101,5)
mul

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [25]:
print(mul.max())
print(mul.min())

100
0


In [27]:
sort=np.sort(mul)
sort

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [28]:
rev=mul[::-1]
rev

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5,   0])

In [30]:
a=np.array([5,5,5])
b=np.array([2,10,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7 15  8]
[ 3 -5  2]
[10 50 15]
[2.5        0.5        1.66666667]


In [32]:
print(np.mean(mul))
print(np.median(mul))
print(np.std(mul))

50.0
50.0
30.276503540974915
